# -*- coding: utf-8 -*-
"""haha.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HXPiZYCLv1M6TvjpsHHPIIr3ihsgMFWG
"""

import random

def userchoice():
  choice=input("Enter rock/paper or scissors")
  choice=choice.lower()
  return choice

def computers_choice():
  number=random.randint(1,3)
  options={1:'rock',2:'papers',3:'scissors'}
  bot_selection=options[number]
  return bot_selection

def result(choice,bot_selection):
  if choice==bot_selection:
    return 'Draw'
  elif choice=='rock' and bot_selection=='scissors':
    return 'Win'
  elif choice=='paper' and bot_selection=='rock':
    return 'Win'
  elif choice=='scissors' and bot_selection=='paper':
    return 'Win'
  else:
    return 'Lose'

yes=True
while yes==True:
  while True:
   getn=userchoice()
   if getn in ['rock','paper','scissors']:
    break

  pcs=computers_choice()
  results=result(getn,pcs)

  print(f"Your selection- {getn}")
  print(f"Computers selection- {pcs}")
  print(f"You - {results}")
  n=input("Enter X to quit or any key to play again")
  if n=='x' or n=='X':
    yes=False